### ISSUE TITLE
1.20.4

### ISSUE THREAD

**Issue by ava852546** [e-im/RandomControl#3]
[06:12:04 INFO]: [RandomControl] Enabling RandomControl v1.1.0
[06:12:04 WARN]: [RandomControl] Failed to initialize compatibility for your server
[06:12:04 WARN]: [RandomControl] If you expect this plugin to work on your server please open an issue
[06:12:04 WARN]: [RandomControl] Current server implementation: git-Purpur-2176 (MC: 1.20.4)
java.lang.ExceptionInInitializerError: Failed to find Random on Entity. No fields with type RandomSource/Random. Not Paper?
        at one.eim.randomcontrol.Compatibility.lambda$static$13(Compatibility.java:73) ~[RandomControl-1.1.0.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at one.eim.randomcontrol.Compatibility.<clinit>(Compatibility.java:73) ~[RandomControl-1.1.0.jar:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at one.eim.randomcontrol.RandomControl.onEnable(RandomControl.java:16) ~[RandomControl-1.1.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
[06:12:04 INFO]: [RandomControl] Disabling RandomControl v1.1.0

**Comment by ava852546** [comment]
[06:15:05 INFO]: [RandomControl] Enabling RandomControl v1.1.0
[06:15:05 WARN]: [RandomControl] Failed to initialize compatibility for your server
[06:15:05 WARN]: [RandomControl] If you expect this plugin to work on your server please open an issue
[06:15:05 WARN]: [RandomControl] Current server implementation: git-Paper-496 (MC: 1.20.4)
java.lang.ExceptionInInitializerError: Failed to find Random on Entity. No fields with type RandomSource/Random. Not Paper?
        at one.eim.randomcontrol.Compatibility.lambda$static$13(Compatibility.java:73) ~[RandomControl-1.1.0.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at one.eim.randomcontrol.Compatibility.<clinit>(Compatibility.java:73) ~[RandomControl-1.1.0.jar:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at one.eim.randomcontrol.RandomControl.onEnable(RandomControl.java:16) ~[RandomControl-1.1.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-496]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
[06:15:05 INFO]: [RandomControl] Disabling RandomControl v1.1.0
